FROM node:20-alpine AS builder

WORKDIR /excalidraw-room

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

COPY tsconfig.json ./
COPY src ./src
RUN yarn build

# Remove dev dependencies in order to copy to the next stage
RUN yarn install --frozen-lockfile --production

FROM node:20-alpine

WORKDIR /excalidraw-room

COPY --from=builder /excalidraw-room/package.json ./
COPY --from=builder /excalidraw-room/yarn.lock ./
COPY --from=builder /excalidraw-room/node_modules ./node_modules
COPY --from=builder /excalidraw-room/dist ./dist

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

# Define build-time arguments
ARG BUILD_PROJECT_NAME=unspecified
ARG BUILD_APP_NAME=unspecified
ARG BUILD_DATE=unspecified
ARG GIT_TAG=unspecified
ARG GIT_COMMIT=unspecified
ARG GIT_SOURCE=unspecified

# Assign to labels
LABEL com.nexpando.project=${BUILD_PROJECT_NAME} \
      com.nexpando.app=${BUILD_PROJECT_NAME} \
      com.nexpando.image.created=${BUILD_DATE} \
      com.nexpando.image.version=${GIT_TAG} \
      com.nexpando.image.revision=${GIT_COMMIT} \
      com.nexpando.image.source=${GIT_SOURCE}

CMD ["node", "/excalidraw-room/dist/index.js"]
